name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 时间 0点 (北京时间早上8点) 执行
  workflow_dispatch: # 允许手动点击按钮触发

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }} # 只有是 Fork 仓库才运行

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: sarperavci/CloudflareBypassForScraping
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.ACTION_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更或冲突，同步失败。"
          echo "请手动解决冲突。"
          exit 1
